//! Addressing and WireGuard configuration generation.
//!
//! The mesh is **full**: every node knows every other. On a three to ten machine
//! homelab that is the right choice - no single chokepoint, and a node going down
//! isolates nobody. A star topology would need less configuration, but would make the
//! hub a single point of failure for all inter-node traffic, which is exactly what
//! this is meant to avoid.

use std::collections::BTreeMap;
use std::net::Ipv4Addr;

use crate::keys::KeyPair;
use crate::{Error, Result};

/// A node of the mesh.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Peer {
    pub name: String,
    /// Address within the mesh network.
    pub mesh_ip: Ipv4Addr,
    pub public_key: String,
    /// Reachable address for establishing the tunnel. Absent for a node behind NAT:
    /// it will have to initiate the connection itself.
    pub endpoint: Option<String>,
}

/// The mesh as a whole.
#[derive(Debug, Clone)]
pub struct MeshConfig {
    /// The mesh private network, a /24. `10.42.0.0` by default.
    network: [u8; 3],
    port: u16,
    peers: BTreeMap<String, Peer>,
}

impl Default for MeshConfig {
    fn default() -> Self {
        Self {
            // 10.42.0.0/24 is unlikely to collide with the home network (usually
            // 192.168.1.0/24) or with Docker's own ranges (172.17-31.0.0/16, and
            // 10.0.0.0/24 for the ingress overlay).
            network: [10, 42, 0],
            port: 51820,
            peers: BTreeMap::new(),
        }
    }
}

impl MeshConfig {
    pub fn new(network: [u8; 3], port: u16) -> Self {
        Self {
            network,
            port,
            peers: BTreeMap::new(),
        }
    }

    pub fn port(&self) -> u16 {
        self.port
    }

    pub fn peers(&self) -> impl Iterator<Item = &Peer> {
        self.peers.values()
    }

    pub fn get(&self, name: &str) -> Option<&Peer> {
        self.peers.get(name)
    }

    /// The mesh network in CIDR notation.
    pub fn cidr(&self) -> String {
        format!(
            "{}.{}.{}.0/24",
            self.network[0], self.network[1], self.network[2]
        )
    }

    /// Adds a node, giving it the first free address.
    ///
    /// Allocation is **deterministic and stable**: a node keeps its address as long as
    /// it is in the mesh. An address that shifted as nodes were added would break the
    /// configurations already deployed on every other node.
    pub fn add_node(
        &mut self,
        name: &str,
        public_key: &str,
        endpoint: Option<String>,
    ) -> Result<Peer> {
        if self.peers.contains_key(name) {
            return Err(Error::DuplicateNode(name.to_string()));
        }

        // .1 is reserved by convention (gateway), .0 and .255 by the protocol. That
        // leaves .2 through .254.
        let occupees: std::collections::BTreeSet<u8> =
            self.peers.values().map(|p| p.mesh_ip.octets()[3]).collect();

        let libre = (2u8..=254)
            .find(|o| !occupees.contains(o))
            .ok_or_else(|| Error::AddressPoolExhausted(253, self.cidr()))?;

        let peer = Peer {
            name: name.to_string(),
            mesh_ip: Ipv4Addr::new(self.network[0], self.network[1], self.network[2], libre),
            public_key: public_key.to_string(),
            endpoint,
        };

        self.peers.insert(name.to_string(), peer.clone());
        Ok(peer)
    }

    /// The `wg-quick` configuration for a given node.
    ///
    /// The private key is passed separately: it lives in the vault and must never
    /// travel through the structure describing the mesh.
    pub fn render_for(&self, node: &str, private_key: &str) -> Option<String> {
        let me = self.peers.get(node)?;
        let mut s = String::new();

        s.push_str("# Generated by Homelabus - do not edit by hand.\n");
        s.push_str(&format!("# node: {}\n\n", me.name));
        s.push_str("[Interface]\n");
        s.push_str(&format!("PrivateKey = {private_key}\n"));
        s.push_str(&format!("Address = {}/24\n", me.mesh_ip));

        // A node with no endpoint is behind NAT: it has nothing to listen for, it
        // will initiate the connections.
        if me.endpoint.is_some() {
            s.push_str(&format!("ListenPort = {}\n", self.port));
        }

        for p in self.peers.values() {
            if p.name == node {
                continue;
            }
            s.push_str(&format!("\n[Peer]\n# {}\n", p.name));
            s.push_str(&format!("PublicKey = {}\n", p.public_key));
            // /32: each peer routes only its own address. A /24 here would make the
            // last declared peer swallow all the mesh traffic.
            s.push_str(&format!("AllowedIPs = {}/32\n", p.mesh_ip));

            if let Some(e) = &p.endpoint {
                s.push_str(&format!("Endpoint = {e}:{}\n", self.port));
            }
            // Keeps the NAT mapping open. Without it, a node behind a home router
            // becomes unreachable after a few minutes of silence.
            s.push_str("PersistentKeepalive = 25\n");
        }

        Some(s)
    }

    /// Rebuilds a mesh from peers that already have addresses.
    ///
    /// 🔴 Addresses are **taken as they are**, never recomputed: a node whose address
    /// changed on reload would invalidate the configurations deployed on every other
    /// machine.
    pub fn from_peers(network: [u8; 3], port: u16, peers: Vec<Peer>) -> Self {
        Self {
            network,
            port,
            peers: peers.into_iter().map(|p| (p.name.clone(), p)).collect(),
        }
    }

    /// The mesh addresses of every node - what Swarm must listen on.
    pub fn advertise_addr_for(&self, node: &str) -> Option<String> {
        self.peers.get(node).map(|p| p.mesh_ip.to_string())
    }
}

/// Creates a node with a fresh key pair.
pub fn provision_node(
    mesh: &mut MeshConfig,
    name: &str,
    endpoint: Option<String>,
) -> Result<(Peer, KeyPair)> {
    let kp = KeyPair::generate();
    let peer = mesh.add_node(name, &kp.public, endpoint)?;
    Ok((peer, kp))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mesh_avec(noms: &[&str]) -> MeshConfig {
        let mut m = MeshConfig::default();
        for n in noms {
            m.add_node(n, &format!("cle-{n}"), Some(format!("{n}.example.fr")))
                .expect("ajout");
        }
        m
    }

    #[test]
    fn addresses_start_at_two() {
        // .0 and .255 are reserved by the protocol, .1 by convention.
        let m = mesh_avec(&["n1", "n2"]);
        assert_eq!(
            m.get("n1").expect("n1").mesh_ip,
            Ipv4Addr::new(10, 42, 0, 2)
        );
        assert_eq!(
            m.get("n2").expect("n2").mesh_ip,
            Ipv4Addr::new(10, 42, 0, 3)
        );
    }

    #[test]
    fn an_address_is_stable_across_additions() {
        // 🔴 An address that shifted as nodes were added would break every
        // configuration already deployed on the other nodes.
        let mut m = mesh_avec(&["n1", "n2"]);
        let avant = m.get("n1").expect("n1").mesh_ip;

        m.add_node("n3", "cle-n3", None).expect("ajout");
        assert_eq!(m.get("n1").expect("n1").mesh_ip, avant);
    }

    #[test]
    fn a_duplicate_node_is_refused() {
        let mut m = mesh_avec(&["n1"]);
        assert!(matches!(
            m.add_node("n1", "autre-cle", None),
            Err(Error::DuplicateNode(_))
        ));
    }

    #[test]
    fn the_default_network_avoids_common_collisions() {
        // 192.168.1.0/24 is the most common home network, and Docker uses
        // 172.17-31.0.0/16 plus 10.0.0.0/24 for the ingress overlay.
        let c = MeshConfig::default().cidr();
        assert_eq!(c, "10.42.0.0/24");
        assert!(!c.starts_with("192.168."));
        assert!(!c.starts_with("172."));
    }

    #[test]
    fn a_configuration_lists_every_other_peer() {
        let m = mesh_avec(&["n1", "n2", "n3"]);
        let c = m.render_for("n1", "MA-CLE-PRIVEE").expect("config");

        assert!(c.contains("PrivateKey = MA-CLE-PRIVEE"));
        assert!(c.contains("Address = 10.42.0.2/24"));
        // The other two, and not itself.
        assert_eq!(c.matches("[Peer]").count(), 2, "{c}");
        assert!(c.contains("cle-n2"));
        assert!(c.contains("cle-n3"));
        assert!(!c.contains("cle-n1"), "a node must not be its own peer");
    }

    #[test]
    fn each_peer_routes_only_its_own_address() {
        // 🔴 A /24 here would make the last declared peer swallow all mesh traffic -
        // the others would become unreachable with no visible error.
        let m = mesh_avec(&["n1", "n2"]);
        let c = m.render_for("n1", "x").expect("config");

        assert!(c.contains("AllowedIPs = 10.42.0.3/32"), "{c}");
        assert!(!c.contains("AllowedIPs = 10.42.0.0/24"));
    }

    #[test]
    fn a_natted_node_does_not_listen_but_keeps_alive() {
        let mut m = MeshConfig::default();
        m.add_node("public", "cle-pub", Some("public.example.fr".into()))
            .expect("ajout");
        m.add_node("derriere-nat", "cle-nat", None).expect("ajout");

        let c = m.render_for("derriere-nat", "x").expect("config");
        assert!(
            !c.contains("ListenPort"),
            "a NATed node has nothing to listen for:\n{c}"
        );
        // But it must keep the NAT mapping open, or it becomes unreachable after a
        // few minutes of silence.
        assert!(c.contains("PersistentKeepalive = 25"));
        assert!(c.contains("Endpoint = public.example.fr:51820"));
    }

    #[test]
    fn a_public_node_listens() {
        let m = mesh_avec(&["n1"]);
        assert!(m
            .render_for("n1", "x")
            .expect("config")
            .contains("ListenPort = 51820"));
    }

    #[test]
    fn an_unknown_node_has_no_configuration() {
        assert!(mesh_avec(&["n1"]).render_for("inconnu", "x").is_none());
    }

    #[test]
    fn the_generated_file_warns_against_hand_editing() {
        let c = mesh_avec(&["n1"]).render_for("n1", "x").expect("config");
        assert!(c.contains("do not edit by hand"));
    }

    #[test]
    fn swarm_advertises_on_the_mesh_address() {
        // 🔴 This is the whole point of the mesh: Swarm must not listen on the
        // public IP, where its 2377/7946/4789 ports would be exposed.
        let m = mesh_avec(&["n1"]);
        assert_eq!(m.advertise_addr_for("n1").as_deref(), Some("10.42.0.2"));
    }

    #[test]
    fn provisioning_generates_a_usable_pair() {
        let mut m = MeshConfig::default();
        let (peer, kp) = provision_node(&mut m, "n1", None).expect("provisionnement");

        assert_eq!(peer.public_key, kp.public);
        // The configuration must be rendered with the matching private key.
        let c = m.render_for("n1", &kp.private).expect("config");
        assert!(c.contains(&kp.private));
        // And above all NOT the private key inside the shared mesh structure.
        assert!(!peer.public_key.contains(&kp.private));
    }

    #[test]
    fn the_pool_is_bounded() {
        let mut m = MeshConfig::default();
        for i in 0..253 {
            m.add_node(&format!("n{i}"), "k", None).expect("ajout");
        }
        assert!(matches!(
            m.add_node("de-trop", "k", None),
            Err(Error::AddressPoolExhausted(..))
        ));
    }
}

#[cfg(test)]
mod tests_persistance {
    use super::*;

    #[test]
    fn reloading_preserves_every_address() {
        // 🔴 Recomputing addresses on reload would reassign them alphabetically,
        // invalidating in one go every configuration deployed elsewhere - without a
        // single error message.
        let mut m = MeshConfig::default();
        m.add_node("zeta", "k1", None).expect("ajout");
        m.add_node("alpha", "k2", None).expect("ajout");

        let avant: Vec<_> = m.peers().map(|p| (p.name.clone(), p.mesh_ip)).collect();

        let recharge = MeshConfig::from_peers([10, 42, 0], 51820, m.peers().cloned().collect());
        let apres: Vec<_> = recharge
            .peers()
            .map(|p| (p.name.clone(), p.mesh_ip))
            .collect();

        assert_eq!(avant, apres);
        // `zeta`, added first, keeps .2 even though it sorts after `alpha`.
        assert_eq!(
            recharge.get("zeta").expect("zeta").mesh_ip,
            std::net::Ipv4Addr::new(10, 42, 0, 2)
        );
    }

    #[test]
    fn a_new_node_takes_the_first_free_address_after_reload() {
        let m = MeshConfig::from_peers(
            [10, 42, 0],
            51820,
            vec![Peer {
                name: "n1".into(),
                mesh_ip: std::net::Ipv4Addr::new(10, 42, 0, 5),
                public_key: "k".into(),
                endpoint: None,
            }],
        );
        let mut m = m;
        let p = m.add_node("n2", "k2", None).expect("ajout");
        // .2 is free: gaps left by a removal get reused.
        assert_eq!(p.mesh_ip, std::net::Ipv4Addr::new(10, 42, 0, 2));
    }

    #[test]
    fn peers_survive_a_json_round_trip() {
        let p = Peer {
            name: "n1".into(),
            mesh_ip: std::net::Ipv4Addr::new(10, 42, 0, 2),
            public_key: "cle".into(),
            endpoint: Some("n1.example.fr".into()),
        };
        let j = serde_json::to_string(&p).expect("serialisable");
        assert_eq!(serde_json::from_str::<Peer>(&j).expect("analysable"), p);
    }
}
