//! L'API compatible addy.io / Bitwarden (§5bis.3).
//!
//! ## Ce que ça permet
//!
//! Bitwarden et Vaultwarden savent générer une adresse jetable au moment où l'on crée
//! un compte sur un site : un bouton dans le formulaire, et l'alias est créé puis
//! rempli. C'est la fonction phare d'addy.io et de SimpleLogin, et c'est ce qui fait la
//! différence entre « je peux créer des aliases » et « j'en crée un à chaque
//! inscription sans y penser ».
//!
//! Pour en profiter sans installer idmail — qui remplacerait l'annuaire de Stalwart et
//! ne pourrait donc pas coexister avec `hlb-mail` — HomelabUS parle le même protocole.
//!
//! ## 🔴 Le contrat est imposé par le CLIENT, pas par nous
//!
//! C'est un point de conception inhabituel : la forme des requêtes et des réponses est
//! fixée par Bitwarden. Elle a été relevée dans son code source
//! (`libs/tools/generator/core/src/integration/addy-io.ts`), pas devinée :
//!
//! ```text
//! POST /api/v1/aliases
//! Authorization: Bearer <jeton>
//! { "domain": "example.fr", "description": "Generated by Bitwarden (site.com)" }
//!
//! → 200/201  { "data": { "email": "site-k7m2p9@example.fr" } }
//! ```
//!
//! Deux conséquences qu'il faut accepter :
//!
//! 1. **La réponse est enveloppée dans `data`.** Bitwarden lit `json.data.email` et
//!    rien d'autre : renvoyer l'adresse à la racine donnerait un alias créé côté
//!    serveur et une erreur muette côté client.
//! 2. **201 autant que 200.** Bitwarden accepte les deux ; on rend 201, qui est le
//!    code juste pour une création.
//!
//! ## 🔴 L'indice vient de la description, et il faut l'en extraire
//!
//! Bitwarden envoie une phrase entière : `"Generated by Bitwarden (amazon.fr)"`. Prise
//! telle quelle, elle donnerait un alias `generated-by-bitwarden-amazon-fr-k7m2p9` —
//! long, illisible, et surtout **identique pour tous les sites**, ce qui détruit
//! l'attribution qui justifie tout le dispositif.
//!
//! [`indice_depuis_description`] en extrait le nom d'hôte.

/// La requête que Bitwarden envoie.
#[derive(Debug, Clone, serde::Deserialize)]
pub struct CreationDemandee {
    /// Domaine sur lequel créer l'alias.
    #[serde(default)]
    pub domain: Option<String>,
    /// Texte libre. Bitwarden y met le site, entre parenthèses.
    #[serde(default)]
    pub description: Option<String>,
}

/// La réponse que Bitwarden attend.
///
/// ⚠️ L'enveloppe `data` n'est pas décorative : le client lit `json.data.email`.
#[derive(Debug, Clone, serde::Serialize)]
pub struct AliasCree {
    pub data: DonneesAlias,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct DonneesAlias {
    /// L'adresse complète, c'est le seul champ que Bitwarden lit.
    pub email: String,
    /// Repris tel quel, pour que l'utilisateur le retrouve dans son gestionnaire.
    pub description: String,
    /// Sert aux clients qui listent ou suppriment ensuite.
    pub id: String,
    pub active: bool,
}

impl AliasCree {
    pub fn new(email: impl Into<String>, description: impl Into<String>) -> Self {
        let email = email.into();
        Self {
            data: DonneesAlias {
                // L'identifiant EST l'adresse : elle est unique par construction, et
                // ça évite d'exposer un identifiant interne dans une API publique.
                id: email.clone(),
                email,
                description: description.into(),
                active: true,
            },
        }
    }
}

/// Extrait un indice utilisable de la description envoyée par le client.
///
/// 🔴 Bitwarden envoie `"Generated by Bitwarden (amazon.fr)"`. Sans extraction,
/// l'indice serait identique pour tous les sites — et l'attribution, seul vrai
/// bénéfice des aliases par destinataire, disparaîtrait.
pub fn indice_depuis_description(description: &str) -> Option<String> {
    // Le nom d'hôte est entre parenthèses chez Bitwarden.
    let brut = match (description.rfind('('), description.rfind(')')) {
        (Some(d), Some(f)) if f > d + 1 => &description[d + 1..f],
        // Pas de parenthèses : on prend le DERNIER mot, pas toute la phrase.
        //
        // 🔴 Constaté par le test : « Website: https://www.fnac.com/panier » donnait
        // l'indice « website-https ». Une phrase entière ne produit jamais un nom
        // d'hôte, et l'alias devenait illisible tout en perdant l'attribution.
        _ => description.split_whitespace().next_back().unwrap_or(""),
    };

    // On retire un préfixe de protocole et un chemin éventuels.
    let hote = brut
        .trim()
        .trim_start_matches("https://")
        .trim_start_matches("http://")
        .split('/')
        .next()
        .unwrap_or("");

    // ⚠️ `www.` et le domaine de premier niveau sont du bruit : `amazon` est un
    // meilleur nom de dossier que `www-amazon-fr`, et c'est ce nom qu'on relira dans
    // six mois.
    let sans_www = hote.trim_start_matches("www.");
    let coeur = sans_www.split('.').next().unwrap_or(sans_www);

    let propre = crate::generation::nettoyer_indice(coeur);

    // Un indice qui ne vient de nulle part ne vaut pas mieux que pas d'indice : mieux
    // vaut un alias purement aléatoire qu'un `generated@` collé sur tout.
    // ⚠️ Un indice identique pour tous les sites ne distingue rien : mieux vaut un
    // alias purement aléatoire qu'un « bitwarden- » collé partout.
    const INUTILES: &[&str] = &["generated", "bitwarden", "by", "website", "http", "https"];
    (!propre.is_empty() && !INUTILES.contains(&propre.as_str())).then_some(propre)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_response_is_wrapped_the_way_bitwarden_reads_it() {
        // 🔴 Le client lit `json.data.email` et rien d'autre. Renvoyer l'adresse à la
        // racine donnerait un alias créé côté serveur et une erreur muette côté
        // client — le pire des deux mondes, puisque l'alias existerait sans que
        // personne ne le sache.
        let r = AliasCree::new("amazon-k7m2p9@example.fr", "Generated by Bitwarden");
        let j = serde_json::to_value(&r).expect("sérialisation");

        assert_eq!(
            j["data"]["email"],
            "amazon-k7m2p9@example.fr",
            "l'adresse doit être sous `data` : {j}"
        );
        assert!(j.get("email").is_none(), "pas à la racine : {j}");
    }

    #[test]
    fn the_hostname_is_extracted_from_bitwardens_sentence() {
        // 🔴 Sans extraction, l'indice serait « generated-by-bitwarden-… » pour TOUS
        // les sites. L'attribution — savoir qui a laissé fuiter l'adresse — n'existerait
        // plus, et c'est tout l'intérêt des aliases par destinataire.
        assert_eq!(
            indice_depuis_description("Generated by Bitwarden (amazon.fr)"),
            Some("amazon".into())
        );
        assert_eq!(
            indice_depuis_description("Website: https://www.fnac.com/panier"),
            Some("fnac".into())
        );
    }

    #[test]
    fn a_bare_hostname_works_too() {
        // Tous les clients n'utilisent pas la forme de Bitwarden.
        assert_eq!(indice_depuis_description("leboncoin.fr"), Some("leboncoin".into()));
        assert_eq!(indice_depuis_description("  Fnac  "), Some("fnac".into()));
    }

    #[test]
    fn a_useless_hint_is_dropped_rather_than_kept() {
        // Mieux vaut un alias purement aléatoire qu'un « generated- » collé sur tout :
        // un indice identique partout ne distingue rien et encombre l'adresse.
        assert_eq!(indice_depuis_description("Generated by Bitwarden"), None);
        assert_eq!(indice_depuis_description(""), None);
        assert_eq!(indice_depuis_description("   "), None);
        assert_eq!(indice_depuis_description("()"), None);
    }

    #[test]
    fn the_www_prefix_and_tld_are_noise() {
        // ⚠️ `amazon` est un meilleur nom de dossier que `www-amazon-fr`, et c'est ce
        // nom qu'on relira dans six mois en cherchant d'où vient un spam.
        assert_eq!(indice_depuis_description("(www.amazon.fr)"), Some("amazon".into()));
        assert_eq!(indice_depuis_description("(shop.example.co.uk)"), Some("shop".into()));
    }

    #[test]
    fn a_request_without_anything_is_still_valid() {
        // Certains clients n'envoient ni domaine ni description : l'alias sera
        // aléatoire, sur le domaine par défaut. C'est dégradé, pas cassé.
        let r: CreationDemandee = serde_json::from_str("{}").expect("corps vide accepté");
        assert!(r.domain.is_none());
        assert!(r.description.is_none());
    }

    #[test]
    fn the_real_bitwarden_body_deserialises() {
        // La forme exacte relevée dans le code de Bitwarden.
        let corps = r#"{"domain":"example.fr","description":"Generated by Bitwarden (site.com)"}"#;
        let r: CreationDemandee = serde_json::from_str(corps).expect("corps réel");
        assert_eq!(r.domain.as_deref(), Some("example.fr"));
        assert_eq!(indice_depuis_description(&r.description.unwrap()), Some("site".into()));
    }

    #[test]
    fn the_id_is_the_address_not_an_internal_identifier() {
        // Exposer un identifiant interne dans une API publique n'apporte rien et
        // couple le client à notre schéma.
        let r = AliasCree::new("x@example.fr", "note");
        assert_eq!(r.data.id, r.data.email);
    }
}
