//! Git mirror of the desired state.
//!
//! Every change is rendered as YAML and committed. That gives three things for free:
//!
//! - a **readable history** of the whole configuration, with diffs;
//! - a **rollback** (`git revert`, then reapply);
//! - a **configuration backup independent of the system itself** - if the state
//!   database is lost, the repository is enough to rebuild from.
//!
//! 🔴 **The database stays the source of truth; Git is a mirror of it.**
//!
//! The reverse - reading Git as the source - would mean handling conflicts,
//! concurrent pushes, three-way reconciliation: reimplementing ArgoCD. What is wanted
//! here is the history, not the full GitOps model.

use std::path::{Path, PathBuf};

use git2::{Repository, Signature};

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("git repository: {0}")]
    Git(#[from] git2::Error),

    #[error("writing {path}: {source}")]
    Io {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },

    #[error("serialising the manifest of \"{app}\": {source}")]
    Serialize {
        app: String,
        #[source]
        source: serde_yaml_ng::Error,
    },
}

pub type Result<T> = std::result::Result<T, Error>;

/// What an export produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportReport {
    /// `None` when nothing had changed: no empty commit is created.
    pub commit: Option<String>,
    pub written: Vec<String>,
    pub removed: Vec<String>,
}

impl ExportReport {
    pub fn changed(&self) -> bool {
        self.commit.is_some()
    }
}

pub struct GitMirror {
    repo: Repository,
    root: PathBuf,
}

impl GitMirror {
    /// Opens the repository, or initialises it if there is none.
    pub fn open_or_init(path: impl AsRef<Path>) -> Result<Self> {
        let root = path.as_ref().to_path_buf();
        let repo = match Repository::open(&root) {
            Ok(r) => r,
            Err(_) => {
                std::fs::create_dir_all(&root).map_err(|source| Error::Io {
                    path: root.clone(),
                    source,
                })?;
                Repository::init(&root)?
            }
        };
        Ok(Self { repo, root })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Writes the desired state and commits what changed.
    ///
    /// For each app, `apps` carries the manifest **frozen at deploy time** and its
    /// status. What gets archived is the deployed state, not today's catalog.
    pub fn export(
        &self,
        apps: &[(String, String, hlb_types::Manifest)],
        message: &str,
    ) -> Result<ExportReport> {
        let dir = self.root.join("apps");
        std::fs::create_dir_all(&dir).map_err(|source| Error::Io {
            path: dir.clone(),
            source,
        })?;

        let mut written = Vec::new();
        let mut expected = std::collections::BTreeSet::new();

        for (name, status, manifest) in apps {
            let file = dir.join(format!("{name}.yaml"));
            expected.insert(format!("{name}.yaml"));

            let yaml = serde_yaml_ng::to_string(manifest).map_err(|source| Error::Serialize {
                app: name.clone(),
                source,
            })?;

            // The header carries what does not fit in the manifest: the status, and
            // the reminder that this file is generated.
            let content = format!(
                "# Generated by Homelabus - deployed state, do not edit by hand.\n\
                 # app: {name}\n# status: {status}\n\n{yaml}"
            );

            // Only rewrite when the content actually changes: otherwise every export
            // would produce a commit and the history would become unreadable.
            let same = std::fs::read_to_string(&file)
                .map(|previous| previous == content)
                .unwrap_or(false);

            if !same {
                std::fs::write(&file, &content).map_err(|source| Error::Io {
                    path: file.clone(),
                    source,
                })?;
                written.push(name.clone());
            }
        }

        // Uninstalled apps leave the mirror but stay in the history, which is
        // precisely the point.
        let mut removed = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&dir) {
            for e in entries.flatten() {
                let name = e.file_name().to_string_lossy().to_string();
                if name.ends_with(".yaml") && !expected.contains(&name) {
                    let _ = std::fs::remove_file(e.path());
                    removed.push(name.trim_end_matches(".yaml").to_string());
                }
            }
        }

        let commit = self.commit_all(message)?;
        Ok(ExportReport {
            commit,
            written,
            removed,
        })
    }

    /// Stages everything and commits, or does nothing when nothing changed.
    fn commit_all(&self, message: &str) -> Result<Option<String>> {
        let mut index = self.repo.index()?;
        index.add_all(["*"].iter(), git2::IndexAddOption::DEFAULT, None)?;
        // `add_all` does not stage deletions: they have to be asked for.
        index.update_all(["*"].iter(), None)?;
        index.write()?;

        let tree_id = index.write_tree()?;
        let tree = self.repo.find_tree(tree_id)?;

        let parent = self
            .repo
            .head()
            .ok()
            .and_then(|h| h.target())
            .and_then(|oid| self.repo.find_commit(oid).ok());

        // Nothing moved: no empty commit, the history must stay readable.
        if let Some(p) = &parent {
            if p.tree_id() == tree_id {
                return Ok(None);
            }
        }

        let sig = Signature::now("Homelabus", "homelabus@localhost")?;
        let parents: Vec<&git2::Commit> = parent.iter().collect();

        let oid = self
            .repo
            .commit(Some("HEAD"), &sig, &sig, message, &tree, &parents)?;
        Ok(Some(oid.to_string()))
    }

    /// The successive versions of an app's manifest, newest first.
    ///
    /// ## 🔴 Why this is read HERE and nowhere else
    ///
    /// `apps.manifest` is OVERWRITTEN on every update: the state keeps only the
    /// current version. Answering "what changed when the app stopped working?" would
    /// therefore need yet another history to be stored - while the Git mirror already
    /// holds one, complete and dated.
    ///
    /// Returns `(short commit, summary, YAML content)`. A version that cannot be read
    /// back is **skipped** rather than returned empty: empty YAML reads as "the
    /// manifest contained nothing", an enormous change that never happened.
    pub fn versions(&self, app: &str, limite: usize) -> Result<Vec<(String, String, String)>> {
        let chemin = format!("apps/{app}.yaml");
        let mut walk = self.repo.revwalk()?;
        if walk.push_head().is_err() {
            return Ok(Vec::new());
        }

        let mut out = Vec::new();
        let mut previous_content: Option<String> = None;

        for oid in walk {
            if out.len() >= limite {
                break;
            }
            let commit = self.repo.find_commit(oid?)?;
            let Ok(arbre) = commit.tree() else { continue };
            let Ok(entree) = arbre.get_path(std::path::Path::new(&chemin)) else {
                continue;
            };
            let Ok(objet) = entree.to_object(&self.repo) else {
                continue;
            };
            let Some(blob) = objet.as_blob() else {
                continue;
            };
            let Ok(content) = std::str::from_utf8(blob.content()) else {
                continue;
            };

            // ⚠️ A commit that does NOT touch this app still carries its file,
            // unchanged. Returning them all would give twenty identical "versions",
            // and the one real change would be lost among them.
            if previous_content.as_deref() == Some(content) {
                continue;
            }
            previous_content = Some(content.to_string());

            out.push((
                commit.id().to_string()[..8].to_string(),
                commit.summary().unwrap_or("").to_string(),
                content.to_string(),
            ));
        }
        Ok(out)
    }

    /// The recent history, for `hlb history`.
    pub fn history(&self, limit: usize) -> Result<Vec<(String, String)>> {
        let mut walk = self.repo.revwalk()?;
        if walk.push_head().is_err() {
            // Empty repository: no history, and that is not an error.
            return Ok(Vec::new());
        }

        let mut out = Vec::new();
        for oid in walk.take(limit) {
            let c = self.repo.find_commit(oid?)?;
            out.push((
                c.id().to_string()[..8].to_string(),
                c.summary().unwrap_or("").to_string(),
            ));
        }
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn only_the_versions_that_actually_changed_are_returned() {
        // 🔴 The trap: a commit that does not touch this app STILL carries its file,
        // unchanged. Returning every commit would give twenty identical "versions",
        // and the single real change would be lost among them.
        let tmp = tempfile::tempdir().expect("temp dir");
        let m = GitMirror::open_or_init(tmp.path()).expect("mirror");

        m.export(
            &[("gitea".into(), "running".into(), manifest("gitea", "1.23"))],
            "install",
        )
        .expect("export 1");

        // A commit that concerns ONLY the other app.
        m.export(
            &[
                ("gitea".into(), "running".into(), manifest("gitea", "1.23")),
                ("immich".into(), "running".into(), manifest("immich", "1.0")),
            ],
            "add immich",
        )
        .expect("export 2");

        m.export(
            &[
                ("gitea".into(), "running".into(), manifest("gitea", "1.24")),
                ("immich".into(), "running".into(), manifest("immich", "1.0")),
            ],
            "update gitea",
        )
        .expect("export 3");

        let v = m.versions("gitea", 10).expect("versions");
        assert_eq!(
            v.len(),
            2,
            "two distinct contents, not three commits: {v:#?}"
        );
        assert!(v[0].2.contains("1.24"), "newest first");
        assert!(v[1].2.contains("1.23"));
    }

    #[test]
    fn an_app_that_was_never_exported_has_no_history_and_no_error() {
        // A missing app is not an error: it simply has no history.
        let tmp = tempfile::tempdir().expect("temp dir");
        let m = GitMirror::open_or_init(tmp.path()).expect("mirror");
        m.export(
            &[("gitea".into(), "running".into(), manifest("gitea", "1"))],
            "install",
        )
        .expect("export");

        assert!(m
            .versions("does-not-exist", 10)
            .expect("versions")
            .is_empty());
    }

    #[test]
    fn an_empty_mirror_is_not_an_error_either() {
        let tmp = tempfile::tempdir().expect("temp dir");
        let m = GitMirror::open_or_init(tmp.path()).expect("mirror");
        assert!(m.versions("gitea", 10).expect("versions").is_empty());
    }

    use super::*;

    fn manifest(name: &str, tag: &str) -> hlb_types::Manifest {
        let y = format!(
            "apiVersion: hlb/v1\nkind: App\nmetadata: {{ name: {name} }}\n\
             spec:\n  image: {{ repo: a/b, tag: \"{tag}\" }}\n"
        );
        serde_yaml_ng::from_str(&y).expect("test manifest")
    }

    fn mirror() -> (tempfile::TempDir, GitMirror) {
        let d = tempfile::tempdir().expect("dir temporaire");
        let m = GitMirror::open_or_init(d.path()).expect("repository");
        (d, m)
    }

    #[test]
    fn an_export_creates_a_commit() {
        let (_d, m) = mirror();
        let apps = vec![("gitea".into(), "running".into(), manifest("gitea", "1.24"))];

        let r = m.export(&apps, "installation de gitea").expect("export");
        assert!(r.changed());
        assert_eq!(r.written, vec!["gitea"]);
        assert!(m.root().join("apps/gitea.yaml").exists());
    }

    #[test]
    fn nothing_changed_means_no_commit() {
        // 🔴 Otherwise every pass of the reconciliation loop would produce a commit,
        // and the history would become unusable.
        let (_d, m) = mirror();
        let apps = vec![("gitea".into(), "running".into(), manifest("gitea", "1.24"))];

        m.export(&apps, "premier").expect("export");
        let second = m.export(&apps, "second").expect("export");

        assert!(!second.changed(), "no commit should have been created");
        assert_eq!(m.history(10).expect("historique").len(), 1);
    }

    #[test]
    fn a_changed_manifest_produces_a_new_commit() {
        let (_d, m) = mirror();
        m.export(
            &[("gitea".into(), "running".into(), manifest("gitea", "1.24"))],
            "v1",
        )
        .expect("export");

        let r = m
            .export(
                &[("gitea".into(), "running".into(), manifest("gitea", "1.25"))],
                "bump to 1.25",
            )
            .expect("export");

        assert!(r.changed());
        let h = m.history(10).expect("history");
        assert_eq!(h.len(), 2);
        assert_eq!(h[0].1, "bump to 1.25", "newest first");
    }

    #[test]
    fn an_uninstalled_app_leaves_the_mirror_but_stays_in_history() {
        let (_d, m) = mirror();
        m.export(
            &[
                ("gitea".into(), "running".into(), manifest("gitea", "1.24")),
                (
                    "vikunja".into(),
                    "running".into(),
                    manifest("vikunja", "0.24"),
                ),
            ],
            "two apps",
        )
        .expect("export");

        let r = m
            .export(
                &[("gitea".into(), "running".into(), manifest("gitea", "1.24"))],
                "uninstall vikunja",
            )
            .expect("export");

        assert_eq!(r.removed, vec!["vikunja"]);
        assert!(!m.root().join("apps/vikunja.yaml").exists());
        // The history keeps it, which is the whole point of the mirror.
        assert_eq!(m.history(10).expect("history").len(), 2);
    }

    #[test]
    fn the_written_file_is_readable_and_flagged_as_generated() {
        let (_d, m) = mirror();
        m.export(
            &[("gitea".into(), "running".into(), manifest("gitea", "1.24"))],
            "x",
        )
        .expect("export");

        let c = std::fs::read_to_string(m.root().join("apps/gitea.yaml")).expect("read");
        assert!(c.contains("do not edit by hand"));
        assert!(c.contains("status: running"));
        // And the manifest must stay readable despite the header.
        let reread: hlb_types::Manifest = serde_yaml_ng::from_str(&c).expect("readable");
        assert_eq!(reread.metadata.name, "gitea");
    }

    #[test]
    fn an_empty_repository_has_no_history() {
        let (_d, m) = mirror();
        assert!(m.history(10).expect("historique").is_empty());
    }

    #[test]
    fn opening_an_existing_repository_keeps_its_history() {
        let d = tempfile::tempdir().expect("temp dir");
        {
            let m = GitMirror::open_or_init(d.path()).expect("repository");
            m.export(
                &[("gitea".into(), "running".into(), manifest("gitea", "1.24"))],
                "premier",
            )
            .expect("export");
        }
        let m = GitMirror::open_or_init(d.path()).expect("reopen");
        assert_eq!(m.history(10).expect("historique").len(), 1);
    }
}
