//! VictoriaMetrics' scrape configuration.
//!
//! ## Why VictoriaMetrics alone, without Prometheus or Alloy
//!
//! Single-node VictoriaMetrics can **scrape** (`-promscrape.config`), store and answer
//! PromQL. The trio of Prometheus + Alloy + remote storage, on a homelab, adds two
//! services to maintain for an identical result. Alloy brings nothing here until there
//! are logs to route.
//!
//! It also uses markedly less memory than Prometheus at equal volume, which matters on
//! a `light` node.
//!
//! ## 🔴 The target everyone forgets
//!
//! The controller exposes `/metrics`, and it is indeed the source. But if
//! VictoriaMetrics scrapes ONLY the controller, then the controller's death makes the
//! scrape go quiet - and a graph that stops looks a lot like a flat graph. That is
//! precisely what the deadman switch ([`crate::deadman`]) catches: the two mechanisms
//! are complementary, and neither replaces the other.

use std::fmt::Write as _;

/// A target to scrape.
#[derive(Debug, Clone)]
pub struct Cible {
    /// Nom du travail de collecte.
    pub job: String,
    /// `host:port`.
    pub adresse: String,
    /// Path of the metrics route.
    pub chemin: String,
    /// Read token, when the route is protected.
    pub jeton: Option<String>,
}

impl Cible {
    /// The controller target.
    ///
    /// ⚠️ `/metrics` is token-protected: without one, VictoriaMetrics scrapes 401s and
    /// the dashboard stays empty without saying why.
    pub fn controller(adresse: impl Into<String>, jeton: Option<String>) -> Self {
        Self {
            job: "hlb-controller".into(),
            adresse: adresse.into(),
            chemin: "/metrics".into(),
            jeton,
        }
    }
}

/// The scrape interval.
///
/// 30 s: Homelabus' metrics change on the scale of a minute (backup age, app state).
/// Scraping every second would multiply storage thirtyfold without revealing more.
pub const INTERVALLE_S: u32 = 30;

/// Produces VictoriaMetrics' `promscrape.config`.
///
/// ⚠️ The token is written **in clear** in this file: it must be installed as a Docker
/// secret, never mounted from a Git repository. It is a READ-ONLY token (`metrics`
/// role), which limits the damage of a leak without cancelling it.
pub fn config_collecte(cibles: &[Cible]) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "# Generated by Homelabus. Do not edit by hand.");
    let _ = writeln!(s, "#");
    let _ = writeln!(
        s,
        "# ⚠️ Ce fichier contient un jeton en clair : pose-le en secret"
    );
    let _ = writeln!(s, "#    Docker secret, never in a Git repository.");
    let _ = writeln!(s, "global:");
    let _ = writeln!(s, "  scrape_interval: {INTERVALLE_S}s");
    let _ = writeln!(s, "scrape_configs:");

    for c in cibles {
        let _ = writeln!(s, "  - job_name: {}", c.job);
        let _ = writeln!(s, "    metrics_path: {}", c.chemin);
        let _ = writeln!(s, "    static_configs:");
        let _ = writeln!(s, "      - targets: ['{}']", c.adresse);
        if let Some(j) = &c.jeton {
            let _ = writeln!(s, "    authorization:");
            let _ = writeln!(s, "      type: Bearer");
            let _ = writeln!(s, "      credentials: '{j}'");
        }
    }
    s
}

/// Data retention.
///
/// 🔴 Thirteen months, not thirty days. The question asked of a metrics history is
/// almost always "was it already like this last year?" - and a short retention answers
/// "I do not know" precisely when it would be useful. The cost is negligible:
/// Homelabus' metrics are few and VictoriaMetrics compresses them heavily.
pub const RETENTION: &str = "13mo";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_token_reaches_the_scrape_config() {
        // 🔴 `/metrics` is token-protected. Without one, VictoriaMetrics scrapes 401s
        // in a loop and the dashboard stays empty - with nothing indicating it is an
        // authentication problem.
        let c = Cible::controller("controller:8080", Some("hlb_lecture_xyz".into()));
        let y = config_collecte(&[c]);

        assert!(y.contains("credentials: 'hlb_lecture_xyz'"), "{y}");
        assert!(y.contains("type: Bearer"), "{y}");
        assert!(y.contains("metrics_path: /metrics"), "{y}");
    }

    #[test]
    fn a_config_without_token_says_nothing_about_authorization() {
        // An empty `authorization` block would break VictoriaMetrics' startup.
        let c = Cible::controller("controller:8080", None);
        let y = config_collecte(&[c]);
        assert!(!y.contains("authorization"), "{y}");
    }

    #[test]
    fn the_config_warns_that_it_holds_a_secret() {
        // A configuration file looks harmless; this one carries a token in clear and
        // would end up in a Git repository without this warning.
        let y = config_collecte(&[Cible::controller("c:8080", Some("x".into()))]);
        assert!(y.contains("never in a Git repository"), "{y}");
    }

    #[test]
    fn retention_covers_more_than_a_year() {
        // 🔴 The question asked of a history is "was it already like this last year?".
        // A 30-day retention answers "I do not know" exactly when it would help.
        assert_eq!(RETENTION, "13mo");
    }

    #[test]
    fn several_targets_are_all_kept() {
        let cibles = vec![
            Cible::controller("c1:8080", None),
            Cible {
                job: "node".into(),
                adresse: "n2:9100".into(),
                chemin: "/metrics".into(),
                jeton: None,
            },
        ];
        let y = config_collecte(&cibles);
        assert!(y.contains("c1:8080"), "{y}");
        assert!(y.contains("n2:9100"), "{y}");
        assert_eq!(y.matches("job_name").count(), 2, "{y}");
    }
}
