//! Enrolling the CrowdSec bouncer.
//!
//! ## Why this is a separate step
//!
//! The Caddyfile needs a bouncer key that **only CrowdSec can produce**, through
//! `cscli bouncers add`. It cannot be invented or guessed: it is generated by the
//! decision engine and recorded in its database.
//!
//! It is shown **once**, at creation. Losing it means deleting the bouncer and
//! enrolling another - hence storing it in the vault as soon as it is obtained, as for
//! OIDC secrets.
//!
//! ## 🔴 An enrolled bouncer protects nothing until Caddy uses it
//!
//! The two halves are independent, and their asymmetry is treacherous:
//!
//! - CrowdSec running without a bouncer **detects** attacks and **blocks** none. The
//!   logs fill with alerts, the dashboard is green, and nobody is ever banned.
//! - A Caddy configured with an invalid key **fails to start**, which is loud and
//!   therefore preferable.
//!
//! The first case is the dangerous one. `status` exists to make it visible.

use crate::{Error, Result};

/// The name the bouncer is registered under in CrowdSec.
///
/// Stable and unique: re-enrolling under the same name fails, which is intended - two
/// bouncers for one Caddy would make it impossible to know which is in service.
pub const BOUNCER_NAME: &str = "hlb-caddy-front";

/// Nom du secret au coffre.
pub const SECRET_NAME: &str = "crowdsec-bouncer-key";

/// How to reach `cscli`.
///
/// CrowdSec runs in a container; `cscli` does not exist on the host. So it is run where
/// it lives.
#[derive(Debug, Clone)]
pub struct Cscli {
    /// Nom du service Swarm portant CrowdSec.
    pub service: String,
}

impl Default for Cscli {
    fn default() -> Self {
        Self {
            service: "crowdsec".into(),
        }
    }
}

impl Cscli {
    pub fn new(service: impl Into<String>) -> Self {
        Self {
            service: service.into(),
        }
    }

    /// Finds the CrowdSec container on this machine.
    ///
    /// ⚠️ In Swarm the container name carries a random suffix (`crowdsec.1.x7k9...`):
    /// filtering on the exact name would find nothing. The label Swarm sets is what is
    /// stable.
    pub async fn container(&self) -> Result<String> {
        let par_etiquette = self
            .docker(&[
                "ps",
                "--filter",
                &format!("label=com.docker.swarm.service.name={}", self.service),
                "--format",
                "{{.ID}}",
            ])
            .await?;

        if let Some(id) = par_etiquette.lines().next().filter(|l| !l.is_empty()) {
            return Ok(id.to_string());
        }

        // Outside Swarm (docker run, compose), the label does not exist.
        let par_nom = self
            .docker(&[
                "ps",
                "--filter",
                &format!("name={}", self.service),
                "--format",
                "{{.ID}}",
            ])
            .await?;

        par_nom
            .lines()
            .next()
            .filter(|l| !l.is_empty())
            .map(|s| s.to_string())
            .ok_or_else(|| {
                Error::CrowdSec(format!(
                    "aucun conteneur CrowdSec en fonctionnement (service « {} »)",
                    self.service
                ))
            })
    }

    /// Enrols the bouncer and returns its key.
    ///
    /// `-o raw`: without it, `cscli` wraps the key in decorative text that would have
    /// to be cut out - and the format of that text changes between versions.
    pub async fn enroll(&self) -> Result<String> {
        let c = self.container().await?;
        let out = self
            .docker(&[
                "exec",
                &c,
                "cscli",
                "bouncers",
                "add",
                BOUNCER_NAME,
                "-o",
                "raw",
            ])
            .await?;

        let cle = out
            .trim()
            .lines()
            .next_back()
            .unwrap_or("")
            .trim()
            .to_string();
        if cle.is_empty() {
            return Err(Error::CrowdSec(
                "cscli returned no key - the bouncer may already exist; \
                 delete it (cscli bouncers delete) or recover its key"
                    .into(),
            ));
        }
        Ok(cle)
    }

    /// Is the bouncer registered on the CrowdSec side?
    pub async fn is_enrolled(&self) -> Result<bool> {
        let c = self.container().await?;
        let out = self
            .docker(&["exec", &c, "cscli", "bouncers", "list", "-o", "raw"])
            .await?;
        Ok(out
            .lines()
            .any(|l| l.split(',').next() == Some(BOUNCER_NAME)))
    }

    async fn docker(&self, args: &[&str]) -> Result<String> {
        let out = tokio::process::Command::new("docker")
            .args(args)
            .output()
            .await
            .map_err(|e| Error::CrowdSec(format!("docker introuvable : {e}")))?;

        if !out.status.success() {
            return Err(Error::CrowdSec(
                String::from_utf8_lossy(&out.stderr).trim().to_string(),
            ));
        }
        Ok(String::from_utf8_lossy(&out.stdout).to_string())
    }
}

/// A plausible bouncer key?
///
/// 🔴 The real danger: an empty or truncated key produces a **syntactically valid**
/// Caddyfile. Caddy starts, the bouncer fails to authenticate, and nothing is blocked
/// any more - with no visible error at all. Better to refuse to generate the config.
pub fn looks_like_key(k: &str) -> bool {
    let k = k.trim();
    k.len() >= 16
        && k.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_plausible_key_is_accepted() {
        assert!(looks_like_key("K7xQ2mNpR4vL8wZa1bC3dE5f"));
        assert!(looks_like_key("abcdefghijklmnop"));
    }

    #[test]
    fn an_empty_or_short_key_is_refused() {
        // 🔴 An empty key gives a valid Caddyfile, a Caddy that starts, and no bans at
        // all - with no error anywhere.
        assert!(!looks_like_key(""));
        assert!(!looks_like_key("   "));
        assert!(!looks_like_key("trop-court"));
    }

    #[test]
    fn decorative_output_is_refused() {
        // Without `-o raw`, cscli wraps the key in text. If that passed, the "key"
        // would be a sentence.
        assert!(!looks_like_key("Api key for 'hlb-caddy-front': abc123"));
        assert!(!looks_like_key("K7xQ2mNpR4vL8wZa\nautre ligne"));
    }

    #[test]
    fn the_bouncer_name_is_stable() {
        // Re-enrolling under a different name would leave two declared bouncers, with
        // no way to know which is actually in service.
        assert_eq!(BOUNCER_NAME, "hlb-caddy-front");
    }
}
